
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Jan 28 21:00:58 CET 2018
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 44;
  public static final int CONST = 3;
  public static final int GRT = 24;
  public static final int GRTEQ = 25;
  public static final int LPAREN = 36;
  public static final int SEMI = 33;
  public static final int CONTINUE = 14;
  public static final int LSS = 26;
  public static final int MINUS = 18;
  public static final int RPAREN = 37;
  public static final int AND = 28;
  public static final int OR = 29;
  public static final int BOOL = 43;
  public static final int COMMA = 34;
  public static final int CLASS = 6;
  public static final int INC = 31;
  public static final int DIV = 20;
  public static final int PLUS = 17;
  public static final int ASSIGN = 30;
  public static final int IF = 7;
  public static final int DOT = 35;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 19;
  public static final int NUMBER = 42;
  public static final int MOD = 21;
  public static final int NEQ = 23;
  public static final int IDENT = 45;
  public static final int BREAK = 5;
  public static final int VOID = 4;
  public static final int EQ = 22;
  public static final int LBRACE = 39;
  public static final int ELSE = 8;
  public static final int LSQUARE = 40;
  public static final int READ = 16;
  public static final int RSQUARE = 41;
  public static final int WHILE = 12;
  public static final int RBRACE = 38;
  public static final int EXTENDS = 13;
  public static final int LEQ = 27;
  public static final int DEC = 32;
  public static final int PRINT = 15;
  public static final int DO = 11;
}

