
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 17 20:08:50 CET 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 42;
  public static final int GRT = 23;
  public static final int GRTEQ = 24;
  public static final int LPAREN = 34;
  public static final int SEMI = 32;
  public static final int CONTINUE = 13;
  public static final int LSS = 25;
  public static final int MINUS = 17;
  public static final int RPAREN = 35;
  public static final int AND = 27;
  public static final int OR = 28;
  public static final int BOOL = 41;
  public static final int COMMA = 33;
  public static final int CLASS = 5;
  public static final int INC = 30;
  public static final int DIV = 19;
  public static final int PLUS = 16;
  public static final int IF = 6;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int EQUAL = 29;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 18;
  public static final int NUMBER = 40;
  public static final int MOD = 20;
  public static final int NEQ = 22;
  public static final int IDENT = 43;
  public static final int BREAK = 4;
  public static final int VOID = 3;
  public static final int EQ = 21;
  public static final int LBRACE = 37;
  public static final int ELSE = 7;
  public static final int LSQUARE = 38;
  public static final int READ = 15;
  public static final int RSQUARE = 39;
  public static final int WHILE = 11;
  public static final int RBRACE = 36;
  public static final int EXTENDS = 12;
  public static final int LEQ = 26;
  public static final int DEC = 31;
  public static final int PRINT = 14;
  public static final int DO = 10;
}

