language: java
jdk:
  openjdk8
  oraclejdk8

notifications:
  email:
    on_success: never
    on_failure: never


script:
  - ant build
  - ant unit_test
  - ant report
  - ant javadoc

before_deploy:
  - pip install --user awscli
  - chmod +x deploy.sh

deploy:
  provider: script
  skip_cleanup: true
  script: "./deploy.sh"
  on:
    all_branches: true
